export enum TypographyTypes {
  'typo-l-large-title-bold' = 'typo-l-large-title-bold',
  'typo-l-large-title-regular' = 'typo-l-large-title-regular',
  'typo-l-title-1-bold' = 'typo-l-title-1-bold',
  'typo-l-title-1-regular' = 'typo-l-title-1-regular',
  'typo-l-title-2-bold' = 'typo-l-title-2-bold',
  'typo-l-title-2-regular' = 'typo-l-title-2-regular',
  'typo-l-title-3-bold' = 'typo-l-title-3-bold',
  'typo-l-title-3-regular' = 'typo-l-title-3-regular',
  'typo-l-title-4-bold' = 'typo-l-title-4-bold',
  'typo-l-title-4-regular' = 'typo-l-title-4-regular',
  'typo-l-title-5-bold' = 'typo-l-title-5-bold',
  'typo-l-title-5-regular' = 'typo-l-title-5-regular',
  'typo-l-subhead-1-bold' = 'typo-l-subhead-1-bold',
  'typo-l-subhead-1-regular' = 'typo-l-subhead-1-regular',
  'typo-l-subhead-2-bold' = 'typo-l-subhead-2-bold',
  'typo-l-subhead-2-regular' = 'typo-l-subhead-2-regular',
  'typo-l-body-bold' = 'typo-l-body-bold',
  'typo-l-body-regular' = 'typo-l-body-regular',
  'typo-l-footnote-bold' = 'typo-l-footnote-bold',
  'typo-l-footnote-regular' = 'typo-l-footnote-regular',
  'typo-l-caption-bold' = 'typo-l-caption-bold',
  'typo-l-caption-regular' = 'typo-l-caption-regular',
  'typo-s-large-title-bold' = 'typo-s-large-title-bold',
  'typo-s-large-title-regular' = 'typo-s-large-title-regular',
  'typo-s-title-1-bold' = 'typo-s-title-1-bold',
  'typo-s-title-1-regular' = 'typo-s-title-1-regular',
  'typo-s-title-2-bold' = 'typo-s-title-2-bold',
  'typo-s-title-2-regular' = 'typo-s-title-2-regular',
  'typo-s-title-3-bold' = 'typo-s-title-3-bold',
  'typo-s-title-3-regular' = 'typo-s-title-3-regular',
  'typo-s-title-4-bold' = 'typo-s-title-4-bold',
  'typo-s-title-4-regular' = 'typo-s-title-4-regular',
  'typo-s-title-5-bold' = 'typo-s-title-5-bold',
  'typo-s-title-5-regular' = 'typo-s-title-5-regular',
  'typo-s-subtitle-1-bold' = 'typo-s-subtitle-1-bold',
  'typo-s-subtitle-1-regular' = 'typo-s-subtitle-1-regular',
  'typo-s-subtitle-2-bold' = 'typo-s-subtitle-2-bold',
  'typo-s-subtitle-2-regular' = 'typo-s-subtitle-2-regular',
  'typo-s-body-bold' = 'typo-s-body-bold',
  'typo-s-body-regular' = 'typo-s-body-regular',
  'typo-s-footnote-bold' = 'typo-s-footnote-bold',
  'typo-s-footnote-regular' = 'typo-s-footnote-regular',
  'typo-s-caption-bold' = 'typo-s-caption-bold',
  'typo-s-caption-regular' = 'typo-s-caption-regular',
}

export const typographyTypes = [
  'typo-l-large-title-bold',
  'typo-l-large-title-regular',
  'typo-l-title-1-bold',
  'typo-l-title-1-regular',
  'typo-l-title-2-bold',
  'typo-l-title-2-regular',
  'typo-l-title-3-bold',
  'typo-l-title-3-regular',
  'typo-l-title-4-bold',
  'typo-l-title-4-regular',
  'typo-l-title-5-bold',
  'typo-l-title-5-regular',
  'typo-l-subhead-1-bold',
  'typo-l-subhead-1-regular',
  'typo-l-subhead-2-bold',
  'typo-l-subhead-2-regular',
  'typo-l-body-bold',
  'typo-l-body-regular',
  'typo-l-footnote-bold',
  'typo-l-footnote-regular',
  'typo-l-caption-bold',
  'typo-l-caption-regular',
  'typo-s-large-title-bold',
  'typo-s-large-title-regular',
  'typo-s-title-1-bold',
  'typo-s-title-1-regular',
  'typo-s-title-2-bold',
  'typo-s-title-2-regular',
  'typo-s-title-3-bold',
  'typo-s-title-3-regular',
  'typo-s-title-4-bold',
  'typo-s-title-4-regular',
  'typo-s-title-5-bold',
  'typo-s-title-5-regular',
  'typo-s-subtitle-1-bold',
  'typo-s-subtitle-1-regular',
  'typo-s-subtitle-2-bold',
  'typo-s-subtitle-2-regular',
  'typo-s-body-bold',
  'typo-s-body-regular',
  'typo-s-footnote-bold',
  'typo-s-footnote-regular',
  'typo-s-caption-bold',
  'typo-s-caption-regular',
];

export const fontFamily = {
  'typo-l-large-title-bold': 'Aeonik',
  'typo-l-large-title-regular': 'Aeonik',
  'typo-l-title-1-bold': 'Aeonik',
  'typo-l-title-1-regular': 'Aeonik',
  'typo-l-title-2-bold': 'Aeonik',
  'typo-l-title-2-regular': 'Aeonik',
  'typo-l-title-3-bold': 'Aeonik',
  'typo-l-title-3-regular': 'Aeonik',
  'typo-l-title-4-bold': 'Aeonik',
  'typo-l-title-4-regular': 'Aeonik',
  'typo-l-title-5-bold': 'Aeonik',
  'typo-l-title-5-regular': 'Aeonik',
  'typo-l-subhead-1-bold': 'Aeonik',
  'typo-l-subhead-1-regular': 'Aeonik',
  'typo-l-subhead-2-bold': 'Aeonik',
  'typo-l-subhead-2-regular': 'Aeonik',
  'typo-l-body-bold': 'Aeonik',
  'typo-l-body-regular': 'Aeonik',
  'typo-l-footnote-bold': 'Aeonik',
  'typo-l-footnote-regular': 'Aeonik',
  'typo-l-caption-bold': 'Aeonik',
  'typo-l-caption-regular': 'Aeonik',
  'typo-s-large-title-bold': 'Aeonik',
  'typo-s-large-title-regular': 'Aeonik',
  'typo-s-title-1-bold': 'Aeonik',
  'typo-s-title-1-regular': 'Aeonik',
  'typo-s-title-2-bold': 'Aeonik',
  'typo-s-title-2-regular': 'Aeonik',
  'typo-s-title-3-bold': 'Aeonik',
  'typo-s-title-3-regular': 'Aeonik',
  'typo-s-title-4-bold': 'Aeonik',
  'typo-s-title-4-regular': 'Aeonik',
  'typo-s-title-5-bold': 'Aeonik',
  'typo-s-title-5-regular': 'Aeonik',
  'typo-s-subtitle-1-bold': 'Aeonik',
  'typo-s-subtitle-1-regular': 'Aeonik',
  'typo-s-subtitle-2-bold': 'Aeonik',
  'typo-s-subtitle-2-regular': 'Aeonik',
  'typo-s-body-bold': 'Aeonik',
  'typo-s-body-regular': 'Aeonik',
  'typo-s-footnote-bold': 'Aeonik',
  'typo-s-footnote-regular': 'Aeonik',
  'typo-s-caption-bold': 'Aeonik',
  'typo-s-caption-regular': 'Aeonik',
};

export const fontSize = {
  'typo-l-large-title-bold': '120px',
  'typo-l-large-title-regular': '120px',
  'typo-l-title-1-bold': '80px',
  'typo-l-title-1-regular': '80px',
  'typo-l-title-2-bold': '64px',
  'typo-l-title-2-regular': '64px',
  'typo-l-title-3-bold': '56px',
  'typo-l-title-3-regular': '56px',
  'typo-l-title-4-bold': '48px',
  'typo-l-title-4-regular': '48px',
  'typo-l-title-5-bold': '40px',
  'typo-l-title-5-regular': '40px',
  'typo-l-subhead-1-bold': '32px',
  'typo-l-subhead-1-regular': '32px',
  'typo-l-subhead-2-bold': '24px',
  'typo-l-subhead-2-regular': '24px',
  'typo-l-body-bold': '16px',
  'typo-l-body-regular': '16px',
  'typo-l-footnote-bold': '14px',
  'typo-l-footnote-regular': '14px',
  'typo-l-caption-bold': '12px',
  'typo-l-caption-regular': '12px',
  'typo-s-large-title-bold': '48px',
  'typo-s-large-title-regular': '48px',
  'typo-s-title-1-bold': '44px',
  'typo-s-title-1-regular': '44px',
  'typo-s-title-2-bold': '40px',
  'typo-s-title-2-regular': '40px',
  'typo-s-title-3-bold': '36px',
  'typo-s-title-3-regular': '36px',
  'typo-s-title-4-bold': '32px',
  'typo-s-title-4-regular': '32px',
  'typo-s-title-5-bold': '24px',
  'typo-s-title-5-regular': '24px',
  'typo-s-subtitle-1-bold': '20px',
  'typo-s-subtitle-1-regular': '20px',
  'typo-s-subtitle-2-bold': '18px',
  'typo-s-subtitle-2-regular': '18px',
  'typo-s-body-bold': '16px',
  'typo-s-body-regular': '16px',
  'typo-s-footnote-bold': '12px',
  'typo-s-footnote-regular': '12px',
  'typo-s-caption-bold': '10px',
  'typo-s-caption-regular': '10px',
};

export const fontWeight = {
  'typo-l-large-title-bold': 700,
  'typo-l-large-title-regular': 400,
  'typo-l-title-1-bold': 700,
  'typo-l-title-1-regular': 400,
  'typo-l-title-2-bold': 700,
  'typo-l-title-2-regular': 400,
  'typo-l-title-3-bold': 700,
  'typo-l-title-3-regular': 400,
  'typo-l-title-4-bold': 700,
  'typo-l-title-4-regular': 400,
  'typo-l-title-5-bold': 700,
  'typo-l-title-5-regular': 400,
  'typo-l-subhead-1-bold': 700,
  'typo-l-subhead-1-regular': 400,
  'typo-l-subhead-2-bold': 700,
  'typo-l-subhead-2-regular': 400,
  'typo-l-body-bold': 700,
  'typo-l-body-regular': 400,
  'typo-l-footnote-bold': 700,
  'typo-l-footnote-regular': 400,
  'typo-l-caption-bold': 700,
  'typo-l-caption-regular': 400,
  'typo-s-large-title-bold': 700,
  'typo-s-large-title-regular': 400,
  'typo-s-title-1-bold': 700,
  'typo-s-title-1-regular': 400,
  'typo-s-title-2-bold': 700,
  'typo-s-title-2-regular': 400,
  'typo-s-title-3-bold': 700,
  'typo-s-title-3-regular': 400,
  'typo-s-title-4-bold': 700,
  'typo-s-title-4-regular': 400,
  'typo-s-title-5-bold': 700,
  'typo-s-title-5-regular': 400,
  'typo-s-subtitle-1-bold': 700,
  'typo-s-subtitle-1-regular': 400,
  'typo-s-subtitle-2-bold': 700,
  'typo-s-subtitle-2-regular': 400,
  'typo-s-body-bold': 700,
  'typo-s-body-regular': 400,
  'typo-s-footnote-bold': 700,
  'typo-s-footnote-regular': 400,
  'typo-s-caption-bold': 700,
  'typo-s-caption-regular': 400,
};

export const letterSpacing = {
  'typo-l-large-title-bold': '0px',
  'typo-l-large-title-regular': '0px',
  'typo-l-title-1-bold': '0px',
  'typo-l-title-1-regular': '0px',
  'typo-l-title-2-bold': '0px',
  'typo-l-title-2-regular': '0px',
  'typo-l-title-3-bold': '0px',
  'typo-l-title-3-regular': '0px',
  'typo-l-title-4-bold': '0px',
  'typo-l-title-4-regular': '0px',
  'typo-l-title-5-bold': '0px',
  'typo-l-title-5-regular': '0px',
  'typo-l-subhead-1-bold': '0px',
  'typo-l-subhead-1-regular': '0px',
  'typo-l-subhead-2-bold': '0px',
  'typo-l-subhead-2-regular': '0px',
  'typo-l-body-bold': '0px',
  'typo-l-body-regular': '0px',
  'typo-l-footnote-bold': '0px',
  'typo-l-footnote-regular': '0px',
  'typo-l-caption-bold': '0px',
  'typo-l-caption-regular': '0px',
  'typo-s-large-title-bold': '0px',
  'typo-s-large-title-regular': '0px',
  'typo-s-title-1-bold': '0px',
  'typo-s-title-1-regular': '0px',
  'typo-s-title-2-bold': '0px',
  'typo-s-title-2-regular': '0px',
  'typo-s-title-3-bold': '0px',
  'typo-s-title-3-regular': '0px',
  'typo-s-title-4-bold': '0px',
  'typo-s-title-4-regular': '0px',
  'typo-s-title-5-bold': '0px',
  'typo-s-title-5-regular': '0px',
  'typo-s-subtitle-1-bold': '0px',
  'typo-s-subtitle-1-regular': '0px',
  'typo-s-subtitle-2-bold': '0px',
  'typo-s-subtitle-2-regular': '0px',
  'typo-s-body-bold': '0px',
  'typo-s-body-regular': '0px',
  'typo-s-footnote-bold': '0px',
  'typo-s-footnote-regular': '0px',
  'typo-s-caption-bold': '0px',
  'typo-s-caption-regular': '0px',
};

export const lineHeight = {
  'typo-l-large-title-bold': '176px',
  'typo-l-large-title-regular': '176px',
  'typo-l-title-1-bold': '96px',
  'typo-l-title-1-regular': '96px',
  'typo-l-title-2-bold': '64px',
  'typo-l-title-2-regular': '64px',
  'typo-l-title-3-bold': '64px',
  'typo-l-title-3-regular': '64px',
  'typo-l-title-4-bold': '56px',
  'typo-l-title-4-regular': '56px',
  'typo-l-title-5-bold': '48px',
  'typo-l-title-5-regular': '48px',
  'typo-l-subhead-1-bold': '40px',
  'typo-l-subhead-1-regular': '40px',
  'typo-l-subhead-2-bold': '32px',
  'typo-l-subhead-2-regular': '32px',
  'typo-l-body-bold': '24px',
  'typo-l-body-regular': '24px',
  'typo-l-footnote-bold': '16px',
  'typo-l-footnote-regular': '16px',
  'typo-l-caption-bold': '16px',
  'typo-l-caption-regular': '16px',
  'typo-s-large-title-bold': '64px',
  'typo-s-large-title-regular': '64px',
  'typo-s-title-1-bold': '56px',
  'typo-s-title-1-regular': '56px',
  'typo-s-title-2-bold': '48px',
  'typo-s-title-2-regular': '48px',
  'typo-s-title-3-bold': '40px',
  'typo-s-title-3-regular': '40px',
  'typo-s-title-4-bold': '40px',
  'typo-s-title-4-regular': '40px',
  'typo-s-title-5-bold': '32px',
  'typo-s-title-5-regular': '32px',
  'typo-s-subtitle-1-bold': '24px',
  'typo-s-subtitle-1-regular': '24px',
  'typo-s-subtitle-2-bold': '24px',
  'typo-s-subtitle-2-regular': '24px',
  'typo-s-body-bold': '24px',
  'typo-s-body-regular': '24px',
  'typo-s-footnote-bold': '16px',
  'typo-s-footnote-regular': '16px',
  'typo-s-caption-bold': '16px',
  'typo-s-caption-regular': '16px',
};
