on:
  workflow_dispatch:
    inputs:
      app:
        type: choice
        description: Application
        options:
        - ""

name: 2. Tag & Release
run-name: Tag & Release by @${{'{'}}{ github.triggering_actor }}

jobs:
  tag_version:
    name: Tag Version
    uses: p6m-dev/github-actions/.github/workflows/cut-tag-javascript.yml@main
    secrets:
      ARTIFACTORY_USERNAME: ${{'{'}}{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_IDENTITY_TOKEN: ${{'{'}}{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}
      UPDATE_MANIFEST_TOKEN: ${{'{'}}{ secrets.UPDATE_MANIFEST_TOKEN }}
      ARTIFACTORY_TOKEN: ${{'{'}}{ secrets.ARTIFACTORY_TOKEN }}
    with:
      NX_APP: ${{'{'}}{ github.event.inputs.app }}
      ARTIFACTORY_REGISTRY: "ybor.jfrog.io"
