on:
  workflow_dispatch:
    inputs:
      app:
        type: choice
        description: Application
        options:
          - ''

name: 'E2E: Regresstion testing'
run-name: E2E Regresstion testing

jobs:
  tag_version:
    name: Tag Version
    uses: p6m-dev/github-actions/.github/workflows/test-e2e.yml@main
    secrets:
      ARTIFACTORY_TOKEN: ${{'{'}}{ secrets.ARTIFACTORY_TOKEN }}
      ARTIFACTORY_USERNAME: ${{'{'}}{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_IDENTITY_TOKEN: ${{'{'}}{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}
      UPDATE_MANIFEST_TOKEN: ${{'{'}}{ secrets.UPDATE_MANIFEST_TOKEN }}
      TESTRAIL_USERNAME: ${{'{'}}{ secrets.TESTRAIL_USERNAME }}
      TESTRAIL_PASSWORD: ${{'{'}}{ secrets.TESTRAIL_PASSWORD }}
      BROWSERSTACK_USERNAME: ${{'{'}}{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{'{'}}{ secrets.BROWSERSTACK_ACCESS_KEY }}
    with:
      environment: 'staging'
      app: ${{'{'}}{ inputs.app }}
      TESTRAIL_ENABLED: ${{'{'}}{ vars.TESTRAIL_ENABLED }}
      TESTRAIL_INSTANCE_NAME: ${{'{'}}{ vars.TESTRAIL_INSTANCE_NAME }}
      TESTRAIL_PROJECT_NAME: ${{'{'}}{ vars.TESTRAIL_PROJECT_NAME }}
      BROWSERSTACK_ENABLED: ${{'{'}}{ vars.BROWSERSTACK_ENABLED }}
